version: '3.6'

services:

  pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql


  accounts-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'PORT=8080'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_accounts:swpt_accounts@pg:5432/${POSTGRES_DB}'
      - 'APP_FETCH_API_URL=http://accounts-server:8080'
      - 'GUNICORN_LOGLEVEL=warning'
      - 'GUNICORN_WORKERS=2'
      - 'GUNICORN_THREADS=1'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'PROTOCOL_PROCESSES=1'
      - 'PROTOCOL_THREADS=1'
      - 'CHORES_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'CHORES_PROCESSES=1'
      - 'CHORES_THREADS=1'
    depends_on:
      - pg


  accounts-server-config:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_accounts:swpt_accounts@pg:5432/${POSTGRES_DB}'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'CHORES_BROKER_URL=amqp://guest:guest@localhost:5672'
    command: configure
    depends_on:
      - pg


volumes:
  pg-data-volume:
