version: '3.6'

services:

  tests-pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql
    ports:
      - $POSTGRES_LOCAL_PORT:5432


  tests-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './swpt_accounts:/usr/src/app/swpt_accounts'
    env_file: .env
    environment:
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'PYTHONBREAKPOINT=web_pdb.set_trace'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_accounts:swpt_accounts@tests-pg:5432/${POSTGRES_DB}'
    command: develop-run-tasks --watch '/usr/src/app/swpt_accounts' tasks:broker
    depends_on:
      - tests-pg
