version: '3.6'

services:

  pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - 'pg-data-volume:/var/lib/postgresql/data'
      - './docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql'
    command: -c log_min_messages=FATAL


  nginx-cache:
    image: nginx:1.19.4
    volumes:
      - 'nginx-cache-volume:/var/lib/nginx/data'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/templates:/etc/nginx/templates'
    environment:
      - 'PORT=80'
      - 'ACCOUNTS_SERVER_URL=http://accounts-server:8080'
      - 'CACHE_KEYS_ZONE=10m'
      - 'CACHE_MAX_SIZE=1g'
      - 'NGINX_ENTRYPOINT_QUIET_LOGS=1'
    ports:
      - 9000:80

  accounts-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'PORT=8080'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_accounts:swpt_accounts@pg:5432/${POSTGRES_DB}'
      - 'APP_FETCH_API_URL=http://nginx-cache:80'
      - 'WEBSERVER_WORKERS=1'
      - 'WEBSERVER_THREADS=3'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'PROTOCOL_PROCESSES=1'
      - 'PROTOCOL_THREADS=3'
      - 'CHORES_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'CHORES_PROCESSES=1'
      - 'CHORES_THREADS=3'
      - 'APP_LOG_LEVEL=warning'
      - 'APP_LOG_FORMAT=json'
      - 'SUBSTITUTE_LOCALHOST_IN_VARS=PROTOCOL_BROKER_URL CHORES_BROKER_URL'


  accounts-server-config:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_accounts:swpt_accounts@pg:5432/${POSTGRES_DB}'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'CHORES_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'SUBSTITUTE_LOCALHOST_IN_VARS=PROTOCOL_BROKER_URL CHORES_BROKER_URL'
    command: configure


volumes:
  pg-data-volume:
  nginx-cache-volume:
